#!/usr/bin/env python
"""
Collect every run in `runs/` into REPORT.md plus contact-sheet images.

    python runners/make_report.py
"""
from __future__ import annotations

import glob
import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

ENGINE_LABEL = {"simp": "3D SIMP (built in)", "pytopo3d": "PyTopo3D",
                "topy": "ToPy"}


def load_records(prefixes=None):
    recs = []
    for rp in sorted(glob.glob(os.path.join(ROOT, "runs", "*", "record.json"))):
        rid = os.path.basename(os.path.dirname(rp))
        if prefixes and not any(rid.startswith(p) for p in prefixes):
            continue
        try:
            recs.append(json.load(open(rp)))
        except Exception as exc:
            print("skipping %s: %s" % (rp, exc))
    return recs


def contact_sheet(records, path, scale=0.62, cols=1):
    from PIL import Image
    ims = []
    for r in records:
        p = os.path.join(ROOT, r["preview"])
        if os.path.exists(p):
            ims.append(Image.open(p))
    if not ims:
        return None
    w = max(i.width for i in ims)
    h = sum(i.height for i in ims)
    sheet = Image.new("RGB", (w, h), "white")
    y = 0
    for i in ims:
        sheet.paste(i, (0, y))
        y += i.height
    sheet = sheet.resize((int(w * scale), int(h * scale)))
    sheet.save(path)
    return path


def table(records):
    head = ("| run | engine | load case | res | vol.frac | p | r_min | keep | "
            "material kept | mass saved | pieces | stiffness kept | "
            "stiff/mass | time |\n"
            "|---|---|---|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|\n")
    rows = []
    for r in records:
        c = r["config"]
        eng = ENGINE_LABEL.get(c.get("engine", "simp"), c.get("engine"))
        vol = r.get("volume_fraction")
        save = r.get("mass_saving")
        comp = r.get("mesh", {}).get("components", 1)
        val = r.get("validation") or {}
        if val.get("unloadable"):
            stiff, sm = "**unloadable**", "–"
        elif "stiffness_ratio_ref" in val:
            stiff = "%.1f%%" % (100 * val["stiffness_ratio_ref"])
            sm = "%.2f" % val["stiffness_per_mass_ref"]
        else:
            stiff = sm = "–"
        rows.append(
            "| `%s` | %s | `%s` | %d | %.2f | %.1f | %.1f | %s | %s mm³ | %s | "
            "%d | %s | %s | %.0f s |"
            % (c["id"], eng, c.get("preset", "-"), c["resolution"],
               vol if vol is not None else float("nan"), c["penal"], c["rmin"],
               "yes" if c.get("keep") else "–",
               format(int(r.get("part_volume_mm3", 0)), ","),
               ("%.0f%%" % (100 * save)) if save is not None else "-",
               comp, stiff, sm, r.get("wall_seconds", 0)))
    return head + "\n".join(rows) + "\n"


def main():
    recs = load_records()
    by_engine = {}
    for r in recs:
        by_engine.setdefault(r["config"].get("engine", "simp"), []).append(r)

    os.makedirs(os.path.join(ROOT, "previews"), exist_ok=True)
    sheets = {}
    for eng, rs in by_engine.items():
        p = os.path.join(ROOT, "previews", "sheet_%s.png" % eng)
        if contact_sheet(rs, p):
            sheets[eng] = os.path.relpath(p, ROOT)

    out = ["# Run log — every optimization in `runs/`",
           "",
           "Auto-generated by `runners/make_report.py`. The written-up findings "
           "are in [`FINDINGS.md`](FINDINGS.md).",
           "",
           "**Reading the last two columns.** `stiffness kept` is the optimized "
           "part's stiffness as a percentage of the *original solid* part's, "
           "both re-solved from scratch by `runners/validate.py` under one "
           "common reference load case (`squash_plus_sway_both`) so every row "
           "is on the same axis. `stiff/mass` divides that by the mass kept: "
           "above 1.0 means the optimized part is stiffer per gram than the "
           "solid original. Blank means the run has not been validated.",
           ""]
    for eng in ("simp", "pytopo3d", "topy"):
        rs = by_engine.get(eng)
        if not rs:
            continue
        out += ["## %s — %d runs" % (ENGINE_LABEL[eng], len(rs)), "", table(rs), ""]
        if eng in sheets:
            out += ["![%s](%s)" % (eng, sheets[eng]), ""]
        out += ["<details><summary>Full settings per run</summary>", ""]
        for r in rs:
            c = r["config"]
            out += ["**`%s`** — %s" % (c["id"], r.get("preset_blurb", "")),
                    "",
                    "```json", json.dumps(c, indent=2, default=str), "```", ""]
        out += ["</details>", ""]

    with open(os.path.join(ROOT, "REPORT.md"), "w") as f:
        f.write("\n".join(out))
    print("wrote REPORT.md with %d runs" % len(recs))


if __name__ == "__main__":
    main()
